### ISSUE TITLE
dependencies among third party packages

### ISSUE THREAD

**Issue by mwerlberger** [ros-infrastructure/bloom#382]
I'm trying to release a chain of third-party packages that depend on each other. E.g. release of gflags, glog and then a custom catkin package. The first two are plain cmake and the jobs are created according to the bloom tutorial for 3rd party packages. Releasing gflags without additional dependencies runs very smooth and all the patches are applied correctly. I only patched the CMakeLists.txt to install the injected package.xml and changed some flags for the build process. The debian package also installs very nicely from the repo server. When now generating a release job on our private buildfarm for glog, the job creation works and the src pkg build. But the bin package fails with the error of not finding gflags. The package is correctly installed but it is not found. The injected package.xml includes a `<depend>` on gflags but the non-catkin build of glog (plain cmake again) ignores the installed gflags (which is located at /opt/ros/jade after installation). The cmake config of glog is only modified to, again, install its package.xml but I did not catkinize it. The gflags dependency is searched via find_package(). As gflags is also not catkinized, there is are no cmake scripts installed in /opt/ros/jade/gflags/ as usual. One possibility would be to inject a catkin section in the cmake but I would prefer to leave the 3rd-party deps as plain cmake. Otherwise a custom setting in glog for the find location might also be an option? What is the usual workflow and what am I missing to have plain cmake inter-dependencies resolved correctly when released with bloom?
Thx,
 -mw

**Comment by mwerlberger** [comment]
btw: what about releasing completely ros agnostic things like plain cmake that are not installed in /opt/ros/XXX but somewhere else? Is this supported/intended?

**Comment by wjwwood** [comment]
So, this is an issue we ran into in the past, where third-party packages which are installed to `/opt/ros/<distro>` cannot be used without depending on `catkin`. We have a line in all of our "debhelper" files like this:

https://github.com/ros-infrastructure/bloom/blob/master/bloom/generators/debian/templates/rules.em#L29
```
if [ -f "@(InstallationPrefix)/setup.sh" ]; then . "@(InstallationPrefix)/setup.sh"; fi && \
```

Which basically means, if there is a `setup.sh` file in the target prefix (defaults to `/opt/ros/<rosdistro>`) then source it before continuing. This file will extend important variables like `PATH`, `PYTHONPATH`, `CMAKE_PREFIX_PATH`, and `PKG_CONFIG_PATH`.

So I believe adding a run dependency on `catkin` in the `package.xml` you inject into your `gflags` and `glog` packages should resolve this issue. The reason why is that before building `glog`, it will install `gflags` which will in turn install `catkin`. Then the `/opt/ros/<distro>/setup.sh` file will exist and it will be sourced before building `glog`. You can see the result of this in the REP about third party packages:

http://www.ros.org/reps/rep-0136.html#have-setup-files-after-installation

I think this is the issue talking about this on `bloom`:

https://github.com/ros-infrastructure/bloom/issues/87

Hopefully that helps. I'm going to close this for now, but feel free to continue to discuss here and we can reopen if needed.

**Comment by mwerlberger** [comment]
Thx,
Actually, this is what I assumed when adding a package.xml in the release repository. This is the current setup, maybe I'm still missing something else:

package.xml in the release repo of `gflags`:
https://github.com/zurich-eye/gflags-release/blob/master/patch_jade/package.xml
as well as in the one from `glog`:
https://github.com/zurich-eye/glog-release/blob/master/patch_jade/package.xml
(as you can see, I played around with different dependency levels and for testing have now a <depend> in gflags for safety...)

Furthermore, I added an install rule in the `CMakeLists.txt` which ends up in the following patch for `gflags`:
https://github.com/zurich-eye/gflags-release/blob/patches/release/jade/gflags/0001-added-some-cmake-flags-for-our-release.patch

For further debugging/testing I also added a manual `gflagsConfig.cmake` and installed it to `share/gflags/cmake` but this also didn't change anything unfortunately.

I'm using `bloom v0.5.20`. On Jenkins I see the logging of checking for a `setup.sh` file but didn't dig in there if it is really found, etc. One custom thing I added to all build jobs is to install git and python-catkin-tools. This is needed by another script but I can remove it again and find another way of injecting it if this could cause the problem that catkin is already installed before resolving gflag's dependencies? The dependency to catkin is there for gflags:says:
```
✗ apt-cache depends ros-jade-gflags                    
ros-jade-gflags
  Depends: libc6
  Depends: libgcc1
  Depends: libstdc++6
  Depends: ros-jade-catkin
```

Jenkins ends up failing when trying to link gflags:
```
18:25:51 /usr/bin/c++  -fPIC -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -D_FORTIFY_SOURCE=2   -shared -Wl,-soname,libglog.so.0.3.4 -o libglog.so.0 CMakeFiles/glog.dir/src/demangle.cc.o CMakeFiles/glog.dir/src/logging.cc.o CMakeFiles/glog.dir/src/raw_logging.cc.o CMakeFiles/glog.dir/src/symbolize.cc.o CMakeFiles/glog.dir/src/utilities.cc.o CMakeFiles/glog.dir/src/vlog_is_on.cc.o CMakeFiles/glog.dir/src/signalhandler.cc.o -lpthread -lgflags 
18:25:51 /usr/bin/ld: cannot find -lgflags
18:25:51 collect2: error: ld returned 1 exit status
18:25:51 make[4]: *** [libglog.so.0] Error 1
18:25:51 make[4]: Leaving directory `/tmp/binarydeb/ros-jade-glog-0.4.0/obj-x86_64-linux-gnu'
18:25:51 make[3]: *** [CMakeFiles/glog.dir/all] Error 2
18:25:51 make[3]: Leaving directory `/tmp/binarydeb/ros-jade-glog-0.4.0/obj-x86_64-linux-gnu'
18:25:51 make[2]: *** [all] Error 2
18:25:51 make[2]: Leaving directory `/tmp/binarydeb/ros-jade-glog-0.4.0/obj-x86_64-linux-gnu'
18:25:51 dh_auto_build: make -j1 returned exit code 2
18:25:51 make[1]: *** [override_dh_auto_build] Error 2
18:25:51 make[1]: Leaving directory `/tmp/binarydeb/ros-jade-glog-0.4.0'
18:25:51 make: *** [build] Error 2
18:25:51 dpkg-buildpackage: error: debian/rules build gave error exit status 2
18:25:51 E: Building failed
18:25:51 Traceback (most recent call last):
18:25:51   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 120, in build_binarydeb
18:25:51     subprocess.check_call(cmd, cwd=source_dir)
18:25:51   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
18:25:51     raise CalledProcessError(retcode, cmd)
18:25:51 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-jade-glog']' returned non-zero exit status 1
```

Any help very much appreciated.
Best,
 Manuel

**Comment by wjwwood** [comment]
Hmm, that may be that the way glog finds gflags is not influenced by the variables we set (we've never tried to install gflags to a custom location before. You could try to figure it out locally by:

- Installing `gflags` to a local folder not in `/usr`
- Trying to build `glog` manually on top of that by just adjusting the environment

Perhaps this will tell you why it doesn't work.

I forgot to answer your other question, which was can you install outside of `/opt/ros/...`. You can. If you look at the generators, there is a `debian` generator, and a `rosdebian` generator. We use the `rosdebian` generator by default, which defaults to an installation prefix of `/opt/ros/<distro>`. You can instead use the normal `debian` generator to generate files in the `debian` folder which install to `/usr` by default. You can try this out locally, for example:

```
william@farl ~/dev/rviz (git:wjwwood-qt5:5094e6e) *
% bloom-generate debian --os-name ubuntu --os-version trusty --ros-distro jade
==> Generating debs for ubuntu:trusty for package(s) ['rviz']
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
Package 'rviz' has dependencies:
Run Dependencies:
  rosdep key           => trusty key

[ ... ]

  catkin               => ['ros-jade-catkin']
==> Placing templates files in the 'debian' folder.
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/rules.em' -> 'debian/rules'

william@farl ~/dev/rviz (git:wjwwood-qt5:5094e6e) *
% cat debian/rules | grep INSTALL_PREFIX
    -DCMAKE_INSTALL_PREFIX="/usr" \

william@farl ~/dev/rviz (git:wjwwood-qt5:5094e6e) *
% rm -rf debian

william@farl ~/dev/rviz (git:wjwwood-qt5:5094e6e) *
% bloom-generate rosdebian --os-name ubuntu --os-version trusty --ros-distro jade
==> Generating debs for ubuntu:trusty for package(s) ['rviz']
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
Package 'rviz' has dependencies:
Run Dependencies:
  rosdep key           => trusty key

[ ... ]

  catkin               => ['ros-jade-catkin']
==> Placing templates files in the 'debian' folder.
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/rules.em' -> 'debian/rules'

william@farl ~/dev/rviz (git:wjwwood-qt5:5094e6e) *
% cat debian/rules | grep INSTALL_PREFIX
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
```

To change it in a release repository, you would just need to change the actions away from the defaults, e.g. change:

(https://github.com/zurich-eye/gflags-release/blob/master/tracks.yaml#L9)
```yaml
    - git-bloom-generate -y rosdebian --prefix release/:{ros_distro} :{ros_distro}
      -i :{release_inc}
```

to this:

```yaml
    - git-bloom-generate -y debian --prefix release/:{ros_distro} :{ros_distro}
      -i :{release_inc}
```

Hopefully that sets you in the right direction.

**Comment by mwerlberger** [comment]
Thanks a lot! This helps a lot.
